CREATE DATABASE crud_example;
USE crud_example;
CREATE TABLE users (
  DPI INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  CORREO VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

